import type { SQLiteDatabase } from 'expo-sqlite';
import { randomUUID } from 'expo-crypto';

export interface SeedGame {
  title: string;
  platform: string;
  genre: string;
  curated_vibe: 'essential' | 'hidden_gem';
  rawg_slug: string;
  curated_desc: string;
}

export const SEED_GAMES: SeedGame[] = [
  // --- PS2 (36 games) ---
  {
    title: 'Final Fantasy X',
    platform: 'ps2',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'final-fantasy-x',
    curated_desc: 'One of the most beloved JRPGs ever. Incredible story, memorable characters, and deep turn-based combat.',
  },
  {
    title: 'Final Fantasy XII',
    platform: 'ps2',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'final-fantasy-xii',
    curated_desc: 'Strategic, MMO-inspired combat with the Gambit system. A more mature, political story set in Ivalice.',
  },
  {
    title: 'Kingdom Hearts',
    platform: 'ps2',
    genre: 'Action RPG',
    curated_vibe: 'essential',
    rawg_slug: 'kingdom-hearts',
    curated_desc: 'Disney meets Final Fantasy. Charming crossover with surprisingly deep action combat.',
  },
  {
    title: 'Kingdom Hearts II',
    platform: 'ps2',
    genre: 'Action RPG',
    curated_vibe: 'essential',
    rawg_slug: 'kingdom-hearts-ii',
    curated_desc: 'Refines everything from the first. Some of the best action combat on PS2.',
  },
  {
    title: 'Metal Gear Solid 2: Sons of Liberty',
    platform: 'ps2',
    genre: 'Stealth',
    curated_vibe: 'essential',
    rawg_slug: 'metal-gear-solid-2-sons-of-liberty',
    curated_desc: 'Postmodern stealth masterpiece. Controversial at launch, now considered ahead of its time.',
  },
  {
    title: 'Metal Gear Solid 3: Snake Eater',
    platform: 'ps2',
    genre: 'Stealth',
    curated_vibe: 'essential',
    rawg_slug: 'metal-gear-solid-3-snake-eater',
    curated_desc: 'Often called the best in the series. Cold War jungle stealth with incredible boss fights.',
  },
  {
    title: 'Shadow of the Colossus',
    platform: 'ps2',
    genre: 'Action Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'shadow-of-the-colossus',
    curated_desc: 'Nothing but massive boss fights in a hauntingly empty world. A genuine work of art.',
  },
  {
    title: 'ICO',
    platform: 'ps2',
    genre: 'Puzzle Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'ico',
    curated_desc: 'Minimalist escort puzzle game. Atmospheric, haunting, and unforgettable.',
  },
  {
    title: "Devil May Cry 3: Dante's Awakening",
    platform: 'ps2',
    genre: 'Action',
    curated_vibe: 'essential',
    rawg_slug: 'devil-may-cry-3',
    curated_desc: 'The blueprint for stylish action games. Tight combat, style switching, brutal difficulty.',
  },
  {
    title: 'Ratchet & Clank',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'ratchet-clank-ps2',
    curated_desc: 'Platforming with absurdly creative weapons. The trilogy starter.',
  },
  {
    title: 'Ratchet & Clank: Going Commando',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'ratchet-clank-going-commando',
    curated_desc: 'Bigger, better, more weapons. Peak PS2 platforming.',
  },
  {
    title: 'Ratchet & Clank: Up Your Arsenal',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'ratchet-clank-up-your-arsenal',
    curated_desc: 'Perfected the formula with online multiplayer.',
  },
  {
    title: 'Jak and Daxter: The Precursor Legacy',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'jak-and-daxter-the-precursor-legacy',
    curated_desc: 'Bright, colourful collectathon platformer from Naughty Dog.',
  },
  {
    title: 'Jak II',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'jak-ii',
    curated_desc: 'Darker, open-world sequel with guns and hover vehicles.',
  },
  {
    title: 'Jak 3',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'jak-3',
    curated_desc: 'Desert wasteland setting, refined combat, satisfying conclusion.',
  },
  {
    title: 'Sly Cooper and the Thievius Raccoonus',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'sly-cooper-and-the-thievius-raccoonus',
    curated_desc: 'Stealth platforming with cel-shaded style and great characters.',
  },
  {
    title: 'Sly 2: Band of Thieves',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'sly-2-band-of-thieves',
    curated_desc: 'Open hub worlds and multiple playable characters.',
  },
  {
    title: 'Sly 3: Honor Among Thieves',
    platform: 'ps2',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'sly-3-honor-among-thieves',
    curated_desc: 'Biggest roster of playable characters, heist missions.',
  },
  {
    title: 'God of War',
    platform: 'ps2',
    genre: 'Action',
    curated_vibe: 'essential',
    rawg_slug: 'god-of-war-2005',
    curated_desc: 'Brutal, cinematic Greek mythology action. Massive set pieces.',
  },
  {
    title: 'God of War II',
    platform: 'ps2',
    genre: 'Action',
    curated_vibe: 'essential',
    rawg_slug: 'god-of-war-ii',
    curated_desc: 'Bigger, more epic sequel. One of the best PS2 games full stop.',
  },
  {
    title: 'Burnout 3: Takedown',
    platform: 'ps2',
    genre: 'Racing',
    curated_vibe: 'essential',
    rawg_slug: 'burnout-3-takedown',
    curated_desc: 'Arguably the best arcade racer ever made. Crashes are half the fun.',
  },
  {
    title: 'SSX 3',
    platform: 'ps2',
    genre: 'Sports',
    curated_vibe: 'essential',
    rawg_slug: 'ssx-3',
    curated_desc: 'Open mountain snowboarding with incredible flow and a killer soundtrack.',
  },
  {
    title: 'Grand Theft Auto: San Andreas',
    platform: 'ps2',
    genre: 'Open World',
    curated_vibe: 'essential',
    rawg_slug: 'grand-theft-auto-san-andreas',
    curated_desc: 'Massive open world across three cities. RPG elements and endless content.',
  },
  {
    title: 'Resident Evil 4',
    platform: 'ps2',
    genre: 'Action Horror',
    curated_vibe: 'essential',
    rawg_slug: 'resident-evil-4-2005',
    curated_desc: 'Redefined third-person action. Tense, replayable, and endlessly influential.',
  },
  {
    title: 'Silent Hill 2',
    platform: 'ps2',
    genre: 'Horror',
    curated_vibe: 'essential',
    rawg_slug: 'silent-hill-2',
    curated_desc: 'Psychological horror at its absolute peak. The story will stay with you.',
  },
  {
    title: 'Silent Hill 3',
    platform: 'ps2',
    genre: 'Horror',
    curated_vibe: 'essential',
    rawg_slug: 'silent-hill-3',
    curated_desc: 'More visceral than SH2 with stunning visuals. Direct sequel to SH1.',
  },
  {
    title: 'Persona 3 FES',
    platform: 'ps2',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'shin-megami-tensei-persona-3-fes',
    curated_desc: 'JRPG meets life sim. Dark themes, incredible music, deep social links.',
  },
  {
    title: 'Persona 4',
    platform: 'ps2',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'shin-megami-tensei-persona-4',
    curated_desc: 'Murder mystery meets high school sim. Warmer tone, equally addictive.',
  },
  {
    title: 'Dragon Quest VIII',
    platform: 'ps2',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'dragon-quest-viii-journey-of-the-cursed-king',
    curated_desc: 'Classic JRPG comfort food with gorgeous cel-shaded visuals.',
  },
  {
    title: 'Shin Megami Tensei: Nocturne',
    platform: 'ps2',
    genre: 'JRPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'shin-megami-tensei-iii-nocturne',
    curated_desc: 'Brutally atmospheric demon-collecting RPG. Post-apocalyptic Tokyo.',
  },
  {
    title: 'Yakuza',
    platform: 'ps2',
    genre: 'Action Adventure',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'yakuza',
    curated_desc: 'Where the series started. Rough but fascinating crime drama.',
  },
  {
    title: 'Yakuza 2',
    platform: 'ps2',
    genre: 'Action Adventure',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'yakuza-2',
    curated_desc: 'Bigger, better sequel. Kamurocho and Sotenbori.',
  },
  {
    title: 'Radiata Stories',
    platform: 'ps2',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'radiata-stories',
    curated_desc: 'Almost every NPC can join your party. Branching paths and charm.',
  },
  {
    title: 'God Hand',
    platform: 'ps2',
    genre: 'Beat-em-up',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'god-hand',
    curated_desc: "Clover Studio's last game. Absurd, punishing cult classic.",
  },
  {
    title: 'Odin Sphere',
    platform: 'ps2',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'odin-sphere',
    curated_desc: 'Gorgeous Vanillaware 2D action RPG with interwoven stories.',
  },
  {
    title: 'Dark Cloud 2',
    platform: 'ps2',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'dark-cloud-2',
    curated_desc: 'Dungeon crawling meets city building meets golf. Genuinely unique.',
  },
  // --- GameCube (20 games) ---
  {
    title: 'The Legend of Zelda: The Wind Waker',
    platform: 'gc',
    genre: 'Action Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'the-legend-of-zelda-the-wind-waker',
    curated_desc: 'Cel-shaded Zelda that aged better than anything from its era.',
  },
  {
    title: 'The Legend of Zelda: Twilight Princess',
    platform: 'gc',
    genre: 'Action Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'the-legend-of-zelda-twilight-princess',
    curated_desc: 'Darker, more traditional Zelda. Epic dungeons and wolf transformation.',
  },
  {
    title: 'Metroid Prime',
    platform: 'gc',
    genre: 'FPS Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'metroid-prime',
    curated_desc: 'First-person exploration masterpiece. Atmosphere through the visor.',
  },
  {
    title: 'Metroid Prime 2: Echoes',
    platform: 'gc',
    genre: 'FPS Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'metroid-prime-2-echoes',
    curated_desc: 'Darker sequel with light/dark world mechanic. Underrated.',
  },
  {
    title: 'Super Smash Bros. Melee',
    platform: 'gc',
    genre: 'Fighting',
    curated_vibe: 'essential',
    rawg_slug: 'super-smash-bros-melee',
    curated_desc: 'Still played competitively 20+ years later.',
  },
  {
    title: 'Resident Evil',
    platform: 'gc',
    genre: 'Horror',
    curated_vibe: 'essential',
    rawg_slug: 'resident-evil',
    curated_desc: 'Gold standard of survival horror remakes.',
  },
  {
    title: 'Paper Mario: The Thousand-Year Door',
    platform: 'gc',
    genre: 'RPG',
    curated_vibe: 'essential',
    rawg_slug: 'paper-mario-the-thousand-year-door',
    curated_desc: "Funny, creative turn-based RPG. One of Nintendo's absolute best.",
  },
  {
    title: 'F-Zero GX',
    platform: 'gc',
    genre: 'Racing',
    curated_vibe: 'essential',
    rawg_slug: 'f-zero-gx',
    curated_desc: 'Blindingly fast futuristic racing. Brutal difficulty, incredible spectacle.',
  },
  {
    title: 'Super Mario Sunshine',
    platform: 'gc',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'super-mario-sunshine',
    curated_desc: 'Tropical Mario with FLUDD water pack. Divisive but charming.',
  },
  {
    title: "Luigi's Mansion",
    platform: 'gc',
    genre: 'Action Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'luigis-mansion',
    curated_desc: 'Ghost-hunting with a vacuum. Cozy and atmospheric.',
  },
  {
    title: 'Star Wars Rogue Squadron II: Rogue Leader',
    platform: 'gc',
    genre: 'Flight Action',
    curated_vibe: 'essential',
    rawg_slug: 'star-wars-rogue-squadron-ii-rogue-leader',
    curated_desc: 'Stunning arcadey Star Wars flight combat.',
  },
  {
    title: "Eternal Darkness: Sanity's Requiem",
    platform: 'gc',
    genre: 'Horror',
    curated_vibe: 'essential',
    rawg_slug: 'eternal-darkness-sanitys-requiem',
    curated_desc: 'Sanity effects break the fourth wall in wild ways.',
  },
  {
    title: 'Tales of Symphonia',
    platform: 'gc',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'tales-of-symphonia',
    curated_desc: 'Great entry to the Tales series with real-time combat.',
  },
  {
    title: 'Fire Emblem: Path of Radiance',
    platform: 'gc',
    genre: 'Tactical RPG',
    curated_vibe: 'essential',
    rawg_slug: 'fire-emblem-path-of-radiance',
    curated_desc: 'One of the best in the series. Permanent death stakes.',
  },
  {
    title: 'Animal Crossing',
    platform: 'gc',
    genre: 'Life Sim',
    curated_vibe: 'essential',
    rawg_slug: 'animal-crossing',
    curated_desc: 'The one that started it all in the West.',
  },
  {
    title: 'Baten Kaitos: Eternal Wings and the Lost Ocean',
    platform: 'gc',
    genre: 'JRPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'baten-kaitos-eternal-wings-and-the-lost-ocean',
    curated_desc: 'Card-based combat with stunning pre-rendered backgrounds.',
  },
  {
    title: 'Chibi-Robo!',
    platform: 'gc',
    genre: 'Adventure',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'chibi-robo',
    curated_desc: 'Tiny robot doing chores. Sounds boring, is incredible.',
  },
  {
    title: 'Skies of Arcadia Legends',
    platform: 'gc',
    genre: 'JRPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'skies-of-arcadia-legends',
    curated_desc: 'Air pirate JRPG with ship battles. One of the best of its era.',
  },
  {
    title: 'Custom Robo',
    platform: 'gc',
    genre: 'Arena Fighter',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'custom-robo',
    curated_desc: 'Deep mech customisation with addictive arena battles.',
  },
  {
    title: 'Gotcha Force',
    platform: 'gc',
    genre: 'Arena Fighter',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'gotcha-force',
    curated_desc: 'Toy battler that\'s perfect for emulation. Wild, chaotic fun.',
  },
  // --- PS1 (22 games) ---
  {
    title: 'Final Fantasy VII',
    platform: 'ps1',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'final-fantasy-vii',
    curated_desc: 'The RPG that changed everything. Iconic characters and that twist.',
  },
  {
    title: 'Final Fantasy IX',
    platform: 'ps1',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'final-fantasy-ix',
    curated_desc: 'A love letter to classic FF. Charming, beautiful, deeply emotional.',
  },
  {
    title: 'Final Fantasy Tactics',
    platform: 'ps1',
    genre: 'Tactical RPG',
    curated_vibe: 'essential',
    rawg_slug: 'final-fantasy-tactics',
    curated_desc: 'Deep political story with incredible tactical combat.',
  },
  {
    title: 'Metal Gear Solid',
    platform: 'ps1',
    genre: 'Stealth',
    curated_vibe: 'essential',
    rawg_slug: 'metal-gear-solid',
    curated_desc: 'Cinematic stealth action that redefined storytelling in games.',
  },
  {
    title: 'Castlevania: Symphony of the Night',
    platform: 'ps1',
    genre: 'Action Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'castlevania-symphony-of-the-night',
    curated_desc: 'Defined the Metroidvania genre. Exploration and RPG depth.',
  },
  {
    title: 'Chrono Cross',
    platform: 'ps1',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'chrono-cross',
    curated_desc: 'Parallel worlds, 40+ characters, one of the best soundtracks ever.',
  },
  {
    title: 'Resident Evil 2',
    platform: 'ps1',
    genre: 'Horror',
    curated_vibe: 'essential',
    rawg_slug: 'resident-evil-2',
    curated_desc: 'Survival horror perfection. Two characters, four scenarios.',
  },
  {
    title: 'Silent Hill',
    platform: 'ps1',
    genre: 'Horror',
    curated_vibe: 'essential',
    rawg_slug: 'silent-hill',
    curated_desc: 'Fog-drenched psychological horror. Atmosphere is unmatched.',
  },
  {
    title: 'Spyro the Dragon',
    platform: 'ps1',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'spyro-the-dragon',
    curated_desc: 'Colourful, relaxing collectathon. Perfect handheld game.',
  },
  {
    title: "Spyro 2: Ripto's Rage",
    platform: 'ps1',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'spyro-2-riptos-rage',
    curated_desc: 'Refined everything. More abilities, better worlds.',
  },
  {
    title: 'Spyro: Year of the Dragon',
    platform: 'ps1',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'spyro-year-of-the-dragon',
    curated_desc: 'Most content, most variety. Great finale.',
  },
  {
    title: 'Crash Bandicoot: Warped',
    platform: 'ps1',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'crash-bandicoot-warped',
    curated_desc: 'The sweet spot of the trilogy. Tight, challenging platforming.',
  },
  {
    title: 'Tekken 3',
    platform: 'ps1',
    genre: 'Fighting',
    curated_vibe: 'essential',
    rawg_slug: 'tekken-3',
    curated_desc: 'One of the greatest fighting games ever made.',
  },
  {
    title: "Tony Hawk's Pro Skater 2",
    platform: 'ps1',
    genre: 'Sports',
    curated_vibe: 'essential',
    rawg_slug: 'tony-hawks-pro-skater-2',
    curated_desc: 'Perfect arcade skating. Legendary level design and soundtrack.',
  },
  {
    title: 'Xenogears',
    platform: 'ps1',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'xenogears',
    curated_desc: 'Mechs, philosophy, religion. Unfinished but unforgettable.',
  },
  {
    title: 'Suikoden II',
    platform: 'ps1',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'suikoden-ii',
    curated_desc: '108 recruitable characters and one of the best villain arcs in RPGs.',
  },
  {
    title: 'Vagrant Story',
    platform: 'ps1',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'vagrant-story',
    curated_desc: "Matsuno's masterpiece. Dense combat and extraordinary writing.",
  },
  {
    title: 'Threads of Fate',
    platform: 'ps1',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'threads-of-fate',
    curated_desc: 'Two characters, two totally different stories. Charming.',
  },
  {
    title: 'Legend of Mana',
    platform: 'ps1',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'legend-of-mana',
    curated_desc: 'Watercolour art with freeform world-building. Beautiful and strange.',
  },
  {
    title: 'Brave Fencer Musashi',
    platform: 'ps1',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'brave-fencer-musashi',
    curated_desc: 'Quirky action adventure with time mechanics. Loads of personality.',
  },
  {
    title: 'Parasite Eve',
    platform: 'ps1',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'parasite-eve',
    curated_desc: 'Survival horror meets RPG in Manhattan. Short, stylish, unique.',
  },
  {
    title: 'Klonoa: Door to Phantomile',
    platform: 'ps1',
    genre: 'Platformer',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'klonoa-door-to-phantomile',
    curated_desc: '2.5D platformer with incredible design and a gut-punch ending.',
  },
  // --- N64 (17 games) ---
  {
    title: 'The Legend of Zelda: Ocarina of Time',
    platform: 'n64',
    genre: 'Action Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'the-legend-of-zelda-ocarina-of-time',
    curated_desc: 'Regularly cited as the greatest game ever made.',
  },
  {
    title: "The Legend of Zelda: Majora's Mask",
    platform: 'n64',
    genre: 'Action Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'the-legend-of-zelda-majoras-mask',
    curated_desc: 'Darker, weirder Zelda with a 3-day time loop.',
  },
  {
    title: 'Super Mario 64',
    platform: 'n64',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'super-mario-64',
    curated_desc: 'Invented 3D platforming. Still a joy to play.',
  },
  {
    title: 'Banjo-Kazooie',
    platform: 'n64',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'banjo-kazooie',
    curated_desc: "Rare's collectathon masterpiece. Witty and wonderful.",
  },
  {
    title: 'Banjo-Tooie',
    platform: 'n64',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'banjo-tooie',
    curated_desc: 'Bigger, more ambitious sequel with interconnected worlds.',
  },
  {
    title: 'Paper Mario',
    platform: 'n64',
    genre: 'RPG',
    curated_vibe: 'essential',
    rawg_slug: 'paper-mario',
    curated_desc: 'Charming, accessible RPG with paper art style.',
  },
  {
    title: 'Star Fox 64',
    platform: 'n64',
    genre: 'Rail Shooter',
    curated_vibe: 'essential',
    rawg_slug: 'star-fox-64',
    curated_desc: 'Arcadey space combat with branching paths. Endlessly replayable.',
  },
  {
    title: 'GoldenEye 007',
    platform: 'n64',
    genre: 'FPS',
    curated_vibe: 'essential',
    rawg_slug: 'goldeneye-007',
    curated_desc: 'Defined console FPS multiplayer. Single-player holds up.',
  },
  {
    title: 'Perfect Dark',
    platform: 'n64',
    genre: 'FPS',
    curated_vibe: 'essential',
    rawg_slug: 'perfect-dark',
    curated_desc: "GoldenEye's successor with more features and sci-fi flair.",
  },
  {
    title: 'F-Zero X',
    platform: 'n64',
    genre: 'Racing',
    curated_vibe: 'essential',
    rawg_slug: 'f-zero-x',
    curated_desc: '30 racers at 60fps. Blazing fast, incredibly tight.',
  },
  {
    title: 'Mario Kart 64',
    platform: 'n64',
    genre: 'Racing',
    curated_vibe: 'essential',
    rawg_slug: 'mario-kart-64',
    curated_desc: 'The definitive kart racer of the era.',
  },
  {
    title: 'Donkey Kong 64',
    platform: 'n64',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'donkey-kong-64',
    curated_desc: 'Massive collectathon. Overwhelming but satisfying.',
  },
  {
    title: 'Mischief Makers',
    platform: 'n64',
    genre: 'Platformer',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'mischief-makers',
    curated_desc: 'Shake shake! 2D Treasure platformer, weird and wonderful.',
  },
  {
    title: 'Mystical Ninja Starring Goemon',
    platform: 'n64',
    genre: 'Action Adventure',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'mystical-ninja-starring-goemon',
    curated_desc: 'Giant robot battles and pure Japanese absurdity.',
  },
  {
    title: 'Sin and Punishment',
    platform: 'n64',
    genre: 'Rail Shooter',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'sin-and-punishment',
    curated_desc: "Treasure's intense on-rails shooter. Japan-only, no Japanese needed.",
  },
  {
    title: 'Blast Corps',
    platform: 'n64',
    genre: 'Action Puzzle',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'blast-corps',
    curated_desc: 'Destroy buildings for a nuclear missile carrier. Unique and addictive.',
  },
  // --- SNES (13 games) ---
  {
    title: 'Chrono Trigger',
    platform: 'snes',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'chrono-trigger',
    curated_desc: 'Often called the greatest RPG ever. Time travel, zero filler.',
  },
  {
    title: 'Final Fantasy VI',
    platform: 'snes',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'final-fantasy-vi',
    curated_desc: 'Ensemble cast, opera scene, Kefka. Peak 2D Final Fantasy.',
  },
  {
    title: 'Super Metroid',
    platform: 'snes',
    genre: 'Action Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'super-metroid',
    curated_desc: 'Atmospheric exploration perfection. Gold standard of the genre.',
  },
  {
    title: 'The Legend of Zelda: A Link to the Past',
    platform: 'snes',
    genre: 'Action Adventure',
    curated_vibe: 'essential',
    rawg_slug: 'the-legend-of-zelda-a-link-to-the-past',
    curated_desc: 'The template for top-down Zelda. Light/dark world brilliance.',
  },
  {
    title: 'Super Mario World',
    platform: 'snes',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'super-mario-world',
    curated_desc: 'Arguably the best 2D platformer ever made.',
  },
  {
    title: 'Earthbound',
    platform: 'snes',
    genre: 'JRPG',
    curated_vibe: 'essential',
    rawg_slug: 'earthbound',
    curated_desc: 'Quirky modern-day RPG. Funny, weird, surprisingly dark.',
  },
  {
    title: 'Secret of Mana',
    platform: 'snes',
    genre: 'Action RPG',
    curated_vibe: 'essential',
    rawg_slug: 'secret-of-mana',
    curated_desc: 'Co-op action RPG with gorgeous sprites.',
  },
  {
    title: 'Super Mario RPG',
    platform: 'snes',
    genre: 'RPG',
    curated_vibe: 'essential',
    rawg_slug: 'super-mario-rpg-legend-of-the-seven-stars',
    curated_desc: 'Mario meets Square. Led to Paper Mario and Mario & Luigi.',
  },
  {
    title: "Donkey Kong Country 2: Diddy's Kong Quest",
    platform: 'snes',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'donkey-kong-country-2-diddys-kong-quest',
    curated_desc: 'Peak DKC. Incredible level design and music.',
  },
  {
    title: 'Mega Man X',
    platform: 'snes',
    genre: 'Action Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'mega-man-x',
    curated_desc: 'Tighter, faster Mega Man with wall jumps and upgrades.',
  },
  {
    title: 'Tactics Ogre: Let Us Cling Together',
    platform: 'snes',
    genre: 'Tactical RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'tactics-ogre-let-us-cling-together',
    curated_desc: 'Deep tactical RPG with branching story. Influenced everything after.',
  },
  {
    title: 'Treasure Hunter G',
    platform: 'snes',
    genre: 'Tactical RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'treasure-hunter-g',
    curated_desc: 'Square tactical RPG (fan translation). Beautiful sprites, unique grid combat.',
  },
  {
    title: 'Terranigma',
    platform: 'snes',
    genre: 'Action RPG',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'terranigma',
    curated_desc: 'You rebuild civilisation. Ambitious and never released in NA.',
  },
  // --- Genesis (4 games) ---
  {
    title: 'Streets of Rage 2',
    platform: 'genesis',
    genre: 'Beat-em-up',
    curated_vibe: 'essential',
    rawg_slug: 'streets-of-rage-2',
    curated_desc: 'Best beat-em-up of the 16-bit era. Incredible soundtrack.',
  },
  {
    title: 'Sonic the Hedgehog 2',
    platform: 'genesis',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'sonic-the-hedgehog-2',
    curated_desc: 'Sonic at his peak. Speed, great level design, iconic zones.',
  },
  {
    title: 'Sonic 3 & Knuckles',
    platform: 'genesis',
    genre: 'Platformer',
    curated_vibe: 'essential',
    rawg_slug: 'sonic-the-hedgehog-3',
    curated_desc: 'The complete Sonic experience. Massive, polished, perfect.',
  },
  {
    title: 'Gunstar Heroes',
    platform: 'genesis',
    genre: 'Run and Gun',
    curated_vibe: 'hidden_gem',
    rawg_slug: 'gunstar-heroes',
    curated_desc: 'Treasure\'s non-stop action masterpiece. Creative bosses throughout.',
  },
];

/**
 * Seeds the database with curated game entries.
 * Skips any game that already exists (matched by rawg_slug + platform).
 */
export async function seedGames(db: SQLiteDatabase): Promise<void> {
  for (const game of SEED_GAMES) {
    const existing = await db.getFirstAsync<{ id: string }>(
      'SELECT id FROM games WHERE rawg_slug = ? AND platform = ?',
      [game.rawg_slug, game.platform]
    );

    if (existing) continue;

    const id = randomUUID();
    await db.runAsync(
      `INSERT INTO games (id, title, platform, genre, curated_vibe, curated_desc, rawg_slug, backlog_status)
       VALUES (?, ?, ?, ?, ?, ?, ?, 'none')`,
      [id, game.title, game.platform, game.genre, game.curated_vibe, game.curated_desc, game.rawg_slug]
    );
  }
}
